app/urls.py
from django.conf.urls import url

from app.views import TeamPointsList

urlpatterns = [

    url(r'', TeamPointsList.as_view(), name='team_list'),
]

hireathena/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('app.urls'),)
]

app/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone


class Team(models.Model):
    """ The team model, contains name and date information """
    name = models.CharField(max_length=250)
    date_created = models.DateTimeField(default=timezone.now, blank=True)
    date_updated = models.DateTimeField(default=timezone.now, blank=True)

    def __str__(self):
        return ("Name: {}, date created: {}, date updated: {}"
                .format(self.name, self.date_created, self.date_updated))


class AUser(models.Model):
    """ The User model, user name and the team they belong to """
    name = models.CharField(max_length=250)
    team = models.ForeignKey(Team, null=True)
    date_created = models.DateTimeField(default=timezone.now, blank=True)
    date_updated = models.DateTimeField(default=timezone.now, blank=True)

    def __str__(self):
        return ("Name: {}, team: {}, date created: {}, date updated: {}"
                .format(self.name, self.team.name, self.date_created,
                        self.date_updated))


class Point(models.Model):
    """ Point model, links to the User and contains the reason for the
    points as well as the date the points were created """
    user = models.ForeignKey(AUser, null=True)
    points = models.IntegerField()
    reason = models.CharField(max_length=250)
    date_created = models.DateTimeField(default=timezone.now, blank=True)

    def __str__(self):
        return ("User: {}, points: {}, reason: {}, date created: {}"
                .format(self.user.name, self.points, self.reason,
                        self.date_created))

app/views.py
from django.db.models import Sum
from django.views.generic import ListView

from app.models import Point


class TeamPointsList(ListView):
    """ View to list the teams and their scores """
    model = Point
    template_name = 'team_list.html'
    queryset = Point.objects.values('user__team__name').order_by().\
        annotate(Sum('points'))

app/templates/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <title>HireAthena: {% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

app/templates/team_list.html
{% extends "base.html" %}

{% block title %}Team list{% endblock %}
{% block content %}
            <h3>
              <label for="amount">The score for each team:</label>
            </h3>

            {% for team in point_list %}
               <ul>
                    Team Name: {{ team.user__team__name }}

                       <ol>Points: {{ team.points__sum }}<br>
                        </ol>
                </ul>
            {% endfor %}
{% endblock %}